* NProj - a CLI for .NET project management

- Commands for managing .NET project files, with a familiar interface.
- Current status: prototyping. Focusing on F# support.
- N.B. managing NuGet packages intentionally excluded: use nuget.exe or paket.

** TODO Initializing a project

#+begin_src
nproj init <path="."> --lang=(csharp|fsharp) --type=(library|exe)
#+end_src

Creates a new project file for that lang at path. If path is a directory, assume the project file has the same name as the directory. Will also create an AssemblyInfo.

** TODO Adding source files/references/other files

#+begin_src
nproj add <...filenames> --project="."
#+end_src

Action depends on the file extension:
- *.cs or *.fs will be added as a compile include
- *.csproj or *.fsproj will be added as reference include
- *.dll will be added as a reference include
- anything else will be added as a data file

If it's a source file (*.fs, *.cs) and it doesn't exist, an empty file will be created.

For F# source file ordering matters, so will follow this rule:
- Program.fs to be the last item if present
- Successive items will be added to the end (but ahead of Program.fs)

In future it might be nice to parse =open= statements and =namespace=, =module= declarations to calculate the correct ordering.

** TODO Removing files

#+begin_src
nproj remove <..filenames> --project="."
nproj rm <..filenames> --project="."
#+end_src

** TODO Moving files

#+begin_src
nproj move <old_filename> <new_filename> --project="."
nproj mv <old_filename> <new_filename> --project="."
#+end_src

** Issues
*** Technical debt
**** TODO Throw away the prototype
**** TODO Tests
*** Third party
Issues with libraries, tooling, etc. Should raise bugs or make fix.
**** TODO The MSBuild library on NuGet does not work from fsx files, only compiled exes
The following code prints "30 items" when called from a compiled exe, but "0 items" when called from the fsx.
#+begin_src fsharp
#!/usr/bin/fsharpi --exec
#r "./Microsoft.Build.dll"
#r "./Microsoft.Build.Framework.dll"

open Microsoft.Build.Evaluation

let file = "/home/vagrant/Working/FSharp.ProjectTemplate.fsproj"
let proj = Project(file)
printfn "%A items" proj.Items.Count
#+end_src
**** TODO in Spacemacs 0.102.x on Ubuntu 14.04, I always get a segfault from the following sequence:
+ SPC f f (some file)
+ SPC w /
+ SPC f f (some other file)
