* NProj - a CLI for .NET project management

- Commands for managing .NET project files, with a familiar interface.
- Current status: prototyping. Focusing on F# support.
- N.B. managing NuGet packages intentionally excluded: use nuget.exe or paket.

** TODO Initializing a project

#+begin_src
nproj init --directory="." --lang=(csharp|fsharp) --type=(library|exe)
#+end_src

Creates a new project file for that lang, taking the same name as the given directory. Also will create an AssemblyInfo.

** TODO Adding source files/references/other files

#+begin_src
nproj add <...filenames> --project="."
#+end_src

Action depends on the file extension:
- *.cs or *.fs will be added as a compile include
- *.csproj or *.fsproj will be added as reference include
- *.dll will be added as a reference include
- anything else will be added as a data file

If it's a source file (*.fs, *.cs) and it doesn't exist, an empty file will be created.

** TODO Removing files

#+begin_src
nproj remove <..filenames> --project="."
nproj rm <..filenames> --project="."
#+end_src

** TODO Moving files

#+begin_src
nproj move <old_filename> <new_filename> --project="."
nproj mv <old_filename> <new_filename> --project="."
#+end_src

* Unrelated notes
** In Spacemacs on Ubuntu 14.04, I always get a segfault from the following sequence:
+ SPC f f (some file)
+ SPC w /
+ SPC f f (some other file)
